name: Build and Publish
on:
  push:
    branches:
      - main # replace with the name of your production branch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: https://npm.pkg.github.com/
        scope: '@modyo'
    - name: Install dependencies with yarn
      # if your project use more than one private registry you cad add it like this:
      # run: |
      #   echo "@fortawesome:registry=https://npm.fontawesome.com/" >> .npmrc
      #   echo "//npm.fontawesome.com/:_authToken=$FORTAWESOME_TOKEN" >> .npmrc
      #   yarn
      # if not do this:
      run: yarn
      env:
        # And add the additional registry token here:
        # FORTAWESOME_TOKEN: ${{secrets.FORTAWESOME_TOKEN}}
        NODE_AUTH_TOKEN: ${{ secrets.TOKEN_REG }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This gets generated automatically
    - name: Build and Push to Modyo Site
      run: yarn modyo-push "$MODYO_WIDGET_NAME"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This gets generated automatically
        MODYO_ACCOUNT_URL: ${{secrets.MODYO_ACCOUNT_URL}}
        MODYO_VERSION: ${{secrets.MODYO_VERSION}}
        MODYO_TOKEN: ${{secrets.MODYO_TOKEN}}
        # Use the site id option
        MODYO_SITE_ID: ${{secrets.MODYO_SITE_ID}}
        # or the site host option, but not both
        MODYO_SITE_HOST: ${{secrets.MODYO_SITE_HOST}}
        MODYO_WIDGET_NAME: ${{secrets.MODYO_WIDGET_NAME}}
    - name: Release Draft
      uses: release-drafter/release-drafter@v5
      with:
        config-name: release-drafter.yml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}